<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="hms-update4" name="SampleTest" tests="3" failures="1" timestamp="28 Mar 2017 11:58:51 GMT" time="0.029" errors="0">
  <testcase name="testMethodTwo" time="0.014" classname="SamplePackage.Test2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at SamplePackage.Test2.testMethodTwo(Test2.java:18)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testMethodTwo -->
  <testcase name="testMethodOne" time="0.001" classname="SamplePackage.Test2"/>
  <testcase name="testMethodThree" time="0.001" classname="SamplePackage.Test2">
    <skipped/>
  </testcase> <!-- testMethodThree -->
</testsuite> <!-- SampleTest -->
